### ISSUE TITLE
Datapackages are not valid

### ISSUE THREAD

**Issue by jnnr** [oemof/oemof-tabular#74]
The datapackages are not valid. You will see validation errors when trying to validate.

From examples/datapackages run:
```
from datapackage import validate

datapackage.validate("dispatch/datapackage.json")
```

```
datapackage.validate("dispatch/datapackage.json")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "envs/oemof-B3/lib/python3.8/site-packages/datapackage/validate.py", line 16, in validate
    Package(descriptor, strict=True)
  File "envs/oemof-B3/lib/python3.8/site-packages/datapackage/package.py", line 105, in __init__
    self.__build()
  File "envs/oemof-B3/lib/python3.8/site-packages/datapackage/package.py", line 300, in __build
    raise exception
  File "envs/oemof-B3/lib/python3.8/site-packages/datapackage/package.py", line 295, in __build
    self.__profile.validate(self.__current_descriptor)
  File "envs/oemof-B3/lib/python3.8/site-packages/datapackage/profile.py", line 67, in validate
    raise exceptions.ValidationError(message, errors=errors)
tableschema.exceptions.ValidationError: There are 2 validation errors (see exception.errors)
```

**Comment by jnnr** [comment]
Hi @gnn, I decided to open this and assigned you because you said that you have that on your radar and have the ambition to fix it when we last met.

**Comment by jnnr** [comment]
Citing gnn:

Im Moment benutzen wir ja das `"foreignKeys"` Property des [Table Schema Descriptors](https://specs.frictionlessdata.io/table-schema/#descriptor), also des `"schema"` Properties einer [Tabular Data Resource](https://specs.frictionlessdata.io/tabular-data-resource/#introduction). Zumindest wenn ich richtig liege. Und wir machen wir auf ein etwas hackige Art und Weise. Wie genau müsst ich nochmal nachschauen.. Aber das Schöne ist, dass sowohl die Spezifikation für `"schema"` als auch die für `"field"` zusätzliche Properties erlauben ("... MAY contain any number of other properties ..."), d.h. wir könnten einfach ein `"foreignColums"` oder `"foreignColumnKeys"` Property einbauen und das benutzen. Das coole ist dann, dass die Heuristik zum Testen ob ein `"foreignKeys"` Eintrag auf eine Spalte zeigt weg fällt und das ganze Explizit wird.

**Comment by jnnr** [comment]
Citing gnn:

Ich hab nochmal nachgeschaut. In der [Dokumentation](https://oemof-tabular.readthedocs.io/en/latest/usage.html#foreign-keys) ist erklärt wie wir "foreignKeys" zweckentfremden. (Auch gleich mit Typo. 🙂 ).
Normalerweise hat das `"reference"` Property ein `"fields"` Property, also `{foreignKeys {reference {fields}}}`, welches angibt, in welchen Spalten der `{foreignKeys {reference {resource}}}` Tabelle die Einträge in den `{foreignKeys {fields}}` Spalten gesucht werden. Wenn man direkt auf eine Spalte einer anderen Tabelle verweisen möchte, wird der Spaltenname ja dynamisch aus der Zelle der Quelltabelle genommen, d.h. der Spaltennamen in der Zieltabelle ergibt sich aus dem was in jeder Zeile in der in `{foreignKeys {fields}}` genannten Spalte steht. In dem Fall ergibt es also keinen Sinn in `{foreignKeys {reference {fields}}}` etwas einzutragen. Daher lassen wir den Eintrag frei und nutzen das Fehlen dieses Eintrags um zu sagen: "Aha. Das ist wohl ein Spaltenschlüssel, also schau ich mal, ob ich in der `{foreignKeys {reference {resource}}}` eine Zielspalte mit dem passenden Namen finde und trage die Werte der Spalte einfach als Liste oder `pandas.Series` under dem zum Quellspaltennamen passenden Attribut ein." Oder wir nutzen eine andere Heuristik, aber so ähnlich sollte das sein.
Um diese Zweckentfremdung jetzt aufzuheben sollten wir ein neues Property `"columnReferences"` einführen, welches:

- Sich auf der gleichen Ebene wie `"foreignKeys"` befindet, also der unter `"schema"`. D.h. man hätte folgende Struktur:

```json
{ "schema":
  { "fields": [...]
  , "foreignKeys": [...]
  , "columnReferences": [...]
  }
}
```

- Kein `"fields"` Property mehr hat, sondern nur `"field"`. Der Grund ist der, dass für Fremdschlüssel mehrere Spalten Sinn ergeben, also `{"foreignKeys": [{"fields": ["foo", "bar"]}]}`, da man dann einfach "Compound Keys" hat. Da wir aber nur eine Spalte referenzieren ergibt auch nur ein Feld als Schlüssel Sinn.
- Den `{reference {ressource}}` Pfad zu `"ressource"` verkürzt. Da wir keine `"fields"` mehr in `"reference"` haben bleibt nur noch das `"ressource"` Property und das kann man auch gleich eine Ebene höher heben.

Als optionales Feature hatte ich mir noch überlegt ein `"index"` Property anzugeben, mit dem man dann eine `pandas.Series` mit ordentlichem Index bauen kann. Das Property wäre entweder ein einfacher String, der die Spalte der referenzierten Tabelle angibt, aus der der Index gebaut wird, ein Array aus Strings, falls der Index aus mehreren Spalten gebaut werden soll, oder ein `{ressource, fields}` Objekt, das Angibt aus welche{r,n} Spalte{,n} einer dritten Tabelle der Index gebaut werden soll. Das kann man aber erstmal weg lassen und den Index einfach aus den `"primaryKeys"` bauen, falls welche angegeben sind.
Letzte Notiz: ich bin mir nicht ganz sicher ob das neue Property `"foreignColumnReferences"` oder nur `"columnReferences"` heißen sollte. Ich tendiere wie man oben sieht zu letzterem, weil es kurz und knapp sagt, wofür das Property da ist. Ersteres wäre allerdings kongruent mit `"foreignKeys"` und ist lang und Umständlich, so dass die Gefahr verringert wird, dass es mit etwas kollidiert, was sich andere als optionales Attribut ausdenken.
Und zum Abschluss noch ein Beispiel, wie das neue Property dann aussehen würde:

```javascript
{ "fields": []
, "foreignKeys": []
  // etc.
, "columnReferences": [
    { "field": "solar-power-output"
    , "ressource": "time-series"
    }
  ]
}
```
